FROM python:3.13.3-slim-bookworm
ENTRYPOINT ["python", "/SOCPRO3.py"]

#--------Old version-------#
#FROM python:3.13.3-slim-bookworm

# Set working directory
#WORKDIR /

# Copy your Python script and directories into the container
#COPY SOCPRO3.py /
#COPY "Drugi_napad_logovi" /Drugi_napad_logovi/
#COPY "Logovi_za_prikaz" /Logovi_za_prikaz/

# Set the default command to run the script
#CMD ["python", "SOCPRO3.py"]
