services:
  splunk-enterprise:
    image: splunk/splunk:latest
    container_name: splunk-enterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Mojasifra123!
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
      - "15140:15140"
      - "1514:1514/udp"
    volumes:
      - splunk_data:/opt/splunk/var
      - ./inputs.conf:/opt/splunk/etc/system/local/inputs.conf

  splunk-uf:
    image: splunk/universalforwarder:latest
    container_name: splunk-uf
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HOME=/opt/splunkforwarder
      - SPLUNK_PASSWORD=Mojasifra123!
      - SPLUNK_SERVER=splunk-enterprise:9997
    volumes:
      - ./splunkuf:/splunkuf               # shared UF‐file directory
      - ./splunk_config:/opt/splunkforwarder/etc/system/local
    depends_on:
      - splunk-enterprise

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  parser-app:
    build: ./parser_app
    container_name: parser-app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=log_queue
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - PARAM_FILE=/placeholder_inputs.txt
    volumes:
      - ./Logovi:/Logovi
      - ./placeholder_inputs.txt:/placeholder_inputs.txt
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true

  log-sender:
    build: ./log_sender
    container_name: log-sender
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=log_queue
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - DEST_HOST=splunk-enterprise
      - UDP_PORT=1514
      - TCP_PORT=15140
      - UF_PATH=/splunkuf/splunkUF.txt
    volumes:
      - ./splunkuf:/splunkuf               # shared UF‐file directory
    depends_on:
      - rabbitmq

  noise-sender:
    build: ./log_sender
    container_name: noise-sender
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=noise_queue
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - DEST_HOST=splunk-enterprise
      - UDP_PORT=1514
      - TCP_PORT=15140
      - UF_PATH=/splunkuf/splunkUF.txt
    volumes:
      - ./splunkuf:/splunkuf
    depends_on:
      - rabbitmq



volumes:
  splunk_data:
