services:
  splunk-server:
    image: splunk/splunk:latest
    container_name: splunk-server
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Mojasifra123!
    ports:
      - "8000:8000" # Web UI
      - "8089:8089" # REST / mgmt port
      - "9997:9997" # Indexer-receiver (UF → IDX)
      - "15140:15140" # **TCP raw events**
      - "1514:1514/udp" # **UDP raw events / syslog**
    volumes:
      - splunk_data:/opt/splunk/var
    tty: true
    stdin_open: true

  splunk-uf:
    image: splunk/universalforwarder:9.4.2
    container_name: splunk-uf
    user: root
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=splunk
      - SPLUNK_PASSWORD=Mojasifra123!
      - SPLUNK_HOME=/opt/splunkforwarder
      - SPLUNK_SERVER=splunk-server:9997 # UF phones home to indexer
    volumes:
      - logovi_za_prikaz:/Logovi_za_prikaz
      - ./splunk_config:/opt/splunkforwarder/etc/system/local
    tty: true
    stdin_open: true
    depends_on:
      - splunk-server

  python-app:
    build: .
    container_name: python-app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - logovi_za_prikaz:/Logovi_za_prikaz
    stdin_open: true
    tty: true
    depends_on:
      - splunk-uf

volumes:
  logovi_za_prikaz:
  splunk_data:
